name: CI

on:
  push:
    branches:
      - main
      - develop
      - web
      - web/feature/*
      - api
      - api/feature/*
  pull_request:
    branches:
      - main
      - develop
      - web
      - web/feature/*
      - api
      - api/feature/*

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v3
        with:
          sha: ${{ github.sha }}

      - name: Install pnpm
        run: npm install -g pnpm@7.28.0

      - name: Install dependencies
        run: pnpm install

      - name: Format
        run: pnpm format:check:api

      - name: Lint
        run: pnpx nx affected --target=lint --parallel=3

      - name: Unit Tests
        run: pnpx nx affected --target=test --parallel=3 --configuration=ci

# TODO to be implemented with React and Cypress
#      - name: E2E Tests
#        run: pnpx nx affected --target=e2e --parallel=3 --configuration=ci

      - name: Build
        run: pnpx nx affected --target=build --parallel=3
